<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="lap1154" failures="1" tests="4" name="SmokeTest" time="32.332" errors="0" timestamp="2023-03-22T04:36:15 IST">
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="verify_invalid_User_invalid_password_login" time="1.496"/>
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="verify_invalid_User_valid_password_login" time="1.103">
    <skipped/>
  </testcase> <!-- verify_invalid_User_valid_password_login -->
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="verify_invalid_User_valid_password_login" time="1.059">
    <skipped/>
  </testcase> <!-- verify_invalid_User_valid_password_login -->
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="verify_invalid_User_valid_password_login" time="1.034">
    <failure type="java.lang.AssertionError" message="expected [Logins] but found [Login]">
      <![CDATA[java.lang.AssertionError: expected [Logins] but found [Login]
at com.TestCases.VerifyUserLoginTest.verify_invalid_User_valid_password_login(VerifyUserLoginTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verify_invalid_User_valid_password_login -->
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="verify_valid_User_Login" time="0.0">
    <ignored/>
  </testcase> <!-- verify_valid_User_Login -->
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="verify_valid_User_invalid_Password_login" time="0.0">
    <ignored/>
  </testcase> <!-- verify_valid_User_invalid_Password_login -->
</testsuite> <!-- SmokeTest -->
